name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build-windows-release:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Generate and Build project
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -G "Visual Studio 17 2022" -A Win32
          cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: samp-gps-win-release
          path: build/Release/GPS.dll

  build-linux-release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          clean: true
          submodules: recursive
          fetch-depth: 0

      - name: Install packages
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-multilib

      - name: Generate build files
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_FLAGS=-m32 -DCMAKE_CXX_FLAGS=-m32

      - name: Build
        run: cmake --build build --config Release

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: samp-gps-linux-release
          path: build/GPS.so
